
#ifndef	DICOM_HEADER_DECLARATIONS
#define	DICOM_HEADER_DECLARATIONS



// Error Codes
#define	DCM_ERROR_OK						 0
#define	DCM_ERROR_INVALID_FILE				-1
#define	DCM_ERROR_FILE_CORRUPTION			-2
#define	DCM_ERROR_HEADER_CODE_INVALID		-3
#define	DCM_ERROR_CANNOT_PARSE_IMAGEINFO	-5	
#define	DCM_ERROR_CANNOT_PARSE_PIXELDATA	-6


// Supported DICOM File Transfer Modes
#define	DCM_NORMALMODE					"1.2.840.10008.1.2"
#define	DCM_EXPLICITMODE				"1.2.840.10008.1.2.1"
#define	DCM_EXPLICITMODE_DEFLATED		"1.2.840.10008.1.2.99"
#define	DCM_EXPLICITMODE_BIGENDIAN		"1.2.840.10008.1.2.2"


// DICOM group codes
enum	headerInfo{	FILEMETAINFO = 0x0002, AQUISITIONGROUPINFO = 0x0018 , IMAGEINFO = 0x0028 , PIXELDATA = 0x7FE0 };
// DICOM undefined length tag field codes
enum	deliminationInfo{	UNDEFINED_LENGTH = 0xFFFFFFFF , DELIMINATOR_GROUP = 0xFFFE , ITEM_TAG = 0xE000 , ITEM_DELIMINATOR_TAG = 0xE00D , SEQUENCE_DELIMINATOR_TAG = 0xE0DD };



#endif	/* DICOM_HEADER_DECLARATIONS */